### ISSUE TITLE
Install part 2 error

### ISSUE THREAD

**Issue by rexshield** [xe5700/kvmd-armbian#13]
Hi, I got error when installing part 2. Already reboot and rerun ./install.sh, the error remains

`|  _ \| |/ /___ /___ // |( _ )  | __ )  _____  __
| |_) | ' /  |_ \ |_ \| |/ _ \  |  _ \ / _ \ \/ /
|  _ <| . \ ___) |__) | | (_) | | |_) | (_) >  <
|_| \_\_|\_\____/____/|_|\___/  |____/ \___/_/\_\

Welcome to Armbian 22.05.0-trunk Bullseye with Linux 5.15.35-rockchip64

No end-user support: built from trunk

System load:   19%              Up time:       7 min
Memory usage:  6% of 1.93G      IP:            192.168.1.9
CPU temp:      74°C             Usage of /:    11% of 15G

[ 0 security updates available, 49 updates total: apt upgrade ]
Last check: 2023-01-07 16:52

[ Menu-driven system configuration (beta): sudo apt update && sudo apt install a                                                                                                                                   rmbian-config ]

root@rk3318-box:~# cd kvmd-armbian/
root@rk3318-box:~/kvmd-armbian# ./install.sh

Running part 2 of PiKVM installer script for Raspbian by @srepac

-> Disabling nginx service, so that we can use kvmd-nginx instead
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable nginx

-> Creating symlinks for use with kvmd python scripts
ln: failed to create symbolic link '/usr/bin/iptables': File exists

-> Creating kvmd-webterm homedir
drwxr-xr-x 2 kvmd-webterm root 4096 Jan  7 16:00 /home/kvmd-webterm
rm: cannot remove '/etc/motd': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/kvmd", line 6, in <module>
    from kvmd.apps.kvmd import main
  File "/usr/local/lib/python3.9/dist-packages/kvmd/apps/__init__.py", line 40, in <module>
    from ..plugins.hid import get_hid_class
  File "/usr/local/lib/python3.9/dist-packages/kvmd/plugins/hid/__init__.py", line 31, in <module>
    class BaseHid(BasePlugin):
  File "/usr/local/lib/python3.9/dist-packages/kvmd/plugins/hid/__init__.py", line 67, in BaseHid
    def set_params(self, keyboard_output: (str | None)=None, mouse_output: (str | None)=None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Did kvmd -m run properly?  [y/n]
`

device is HK1 Super RK3318 2GB RAM 16GB ROM running Armbian 22.05.0-trunk Bullseye with Linux 5.15.35-rockchip64

output of systemctl status kvmd-otg.service
`root@rk3318-box:~/kvmd-armbian# systemctl status kvmd-otg.service
● kvmd-otg.service - PiKVM - OTG setup
     Loaded: loaded (/lib/systemd/system/kvmd-otg.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-01-07 16:56:48 WIB; 8min ago
   Main PID: 2066 (code=exited, status=1/FAILURE)
        CPU: 1.092s

Warning: journal has been rotated since unit was started, output may be incomplete.
`

output of journalctl -x
`root@rk3318-box:~/kvmd-armbian# journalctl -x
-- Journal begins at Sat 2023-01-07 16:29:29 WIB, ends at Sat 2023-01-07 17:06:28 WIB. --
Jan 07 16:29:29 rk3318-box systemd[1]: kvmd.service: Scheduled restart job, restart counter is at 154.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ Automatic restarting of the unit kvmd.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Jan 07 16:29:29 rk3318-box systemd[1]: Stopped PiKVM - The main daemon.
░░ Subject: A stop job for unit kvmd.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A stop job for unit kvmd.service has finished.
░░
░░ The job identifier is 10248 and the job result is done.
Jan 07 16:29:29 rk3318-box systemd[1]: kvmd.service: Consumed 1.541s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit kvmd.service completed and consumed the indicated resources.
Jan 07 16:29:29 rk3318-box systemd[1]: Started PiKVM - The main daemon.
░░ Subject: A start job for unit kvmd.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit kvmd.service has finished successfully.
░░
░░ The job identifier is 10248.
Jan 07 16:29:30 rk3318-box kvmd[2335]: Traceback (most recent call last):
Jan 07 16:29:30 rk3318-box kvmd[2335]:   File "/usr/bin/kvmd", line 6, in <module>
Jan 07 16:29:30 rk3318-box kvmd[2335]:     from kvmd.apps.kvmd import main
Jan 07 16:29:30 rk3318-box kvmd[2335]:   File "/usr/local/lib/python3.9/dist-packages/kvmd/apps/__init__.py", line 40, in <module>
Jan 07 16:29:30 rk3318-box kvmd[2335]:     from ..plugins.hid import get_hid_class
Jan 07 16:29:30 rk3318-box kvmd[2335]:   File "/usr/local/lib/python3.9/dist-packages/kvmd/plugins/hid/__init__.py", line 31, in <module>
Jan 07 16:29:30 rk3318-box kvmd[2335]:     class BaseHid(BasePlugin):
Jan 07 16:29:30 rk3318-box kvmd[2335]:   File "/usr/local/lib/python3.9/dist-packages/kvmd/plugins/hid/__init__.py", line 67, in BaseHid
Jan 07 16:29:30 rk3318-box kvmd[2335]:     def set_params(self, keyboard_output: (str | None)=None, mouse_output: (str | None)=None) -> None:
Jan 07 16:29:30 rk3318-box kvmd[2335]: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Jan 07 16:29:30 rk3318-box systemd[1]: kvmd.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
lines 1-43
`

**Comment by peacokswiss** [comment]
Maybee have a look in,  https://github.com/xe5700/kvmd-armbian/issues/12

and some trubles... about kernel dtb etc...

**Comment by rexshield** [comment]
> 

> Maybee have a look in, #12
> 
> and some trubles... about kernel dtb etc...

hello, I tried changing dtb with armbian-config, but the problem persists. I also tried wget the new install.sh and config.sh from your site. chmod +x then run it. I got the same error.

I need some more details with these steps, please. How do I modify my dtb file to enable otg feature? Where to change dr mode? Thank you
> Step 2
> Modify your dtb file to enable otg feature. Change dr_mode from host to peripheral for otg usb port.
> If you use rk322x (rk3228A rk3228B rk3229) series chipset, you can use dtb/4.4/rk332x-box.dtb

**Comment by peacokswiss** [comment]
i said,   that the new install.sh and config.sh  works,  on proper kernel with all neded modules enabled, and then you need a dtb file that show the moudles the hardware...  

But if you don't believe...  Shure your kernel is also wrong,  is all very difficult....  an dtb mybee or all togheter..  then shitt happens....

For Handy make the dtb  stuff:

first make a backup  like mv    blalbalhardware.dtb blalbalhardware.dtb,bak
(for your security )  

dtc -I  dtb  -O dts -f   inputfile.dtb  -o  outputfile.dts  

so now you can edit by nano  outputfile.dts  ,,  ready  saved the changes?

So we compile back:

dtc -I dts -O dtb -f  inputfiled.dts  -o  outputfile.dtb


enjoy

**Comment by peacokswiss** [comment]
i can feel you go also the long way...   from try&error,   to find out, it depends now only on correct kernel and dtb....

wich we not should make,,     so fire all personal out ;)

**Comment by peacokswiss** [comment]
If you go this way ,  you need sometimes rewrite the sdcard... shure..   mksdcard y'll find also on my server.... saver write sdcards.. ok ;)  (Be Carfuell..  is danger tool)

**Comment by peacokswiss** [comment]
Here you have an ordinary quick explanation.. but if you want to know exactly, you have to study your electronics yourself....

ok cue...

http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/Howtomake_theDTB_Files%20correct_ForPiKVM.pdf

byby
