### ISSUE TITLE
Issue with kvmd on OrangePi Zero

### ISSUE THREAD

**Issue by pecuna** [xe5700/kvmd-armbian#16]
Hi all,
I am trying to install on OrangePi Zero.
But have issues with running kvmd, it gives me:

> kvmd -m
Traceback (most recent call last):
  File "/usr/local/bin/kvmd", line 6, in <module>
    from kvmd.apps.kvmd import main
  File "/usr/local/lib/python3.9/dist-packages/kvmd/apps/__init__.py", line 40, in <module>
    from ..plugins.hid import get_hid_class
  File "/usr/local/lib/python3.9/dist-packages/kvmd/plugins/hid/__init__.py", line 31, in <module>
    class BaseHid(BasePlugin):
  File "/usr/local/lib/python3.9/dist-packages/kvmd/plugins/hid/__init__.py", line 67, in BaseHid
    def set_params(self, keyboard_output: (str | None)=None, mouse_output: (str | None)=None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

I am not sure I edited correctly the dtb file... Didn't find anything on the topic...
@MrSuicideParrot could you please reveal the secret regarding using this board for the purpose?

**Comment by MrSuicideParrot** [comment]
Hi! I haven't updated my orangepi zero kvmd in a while, so something might have changed.
However, your issue might be related to #6 since you are using python 3.9.

**Comment by xe5700** [comment]
This is a bug, dev bench fix it. You can use rm -rf /usr/local/lib/python3.9/dist-packages/kvmd to remove packages from offical repo. This script install old version package default in site-packages path. New version after kvmd 3.142 only support python 3.10.

**Comment by pecuna** [comment]
I have this in the config:
export KVMD_VERSION="3.142" # LAST KVMD VERSION SUPPORTS PYTHON3.9

So I have to remove the kvmd and use the dev branch of this repo in order to get it working?

**Comment by xe5700** [comment]
Check /usr/local/lib/python3.9/dist-packages/kvmd-3.142-py3.9.egg this path exists. If script not work you can install kvmd by you self from https://github.com/pikvm/kvmd/tree/v3.142 then running setup.py remove all other kvmd package in python path.

**Comment by naxeras** [comment]
Hi,

Any help to install in OrangePi Zero?

I´m using a fresh install of Debian Buster, after restarting and launching the script it asks me to restart again.

Regards

**Comment by peacokswiss** [comment]
It works only on Bookworm now,  python3.11  ... 
See https://github.com/xe5700/kvmd-armbian/issues/22     pls
