### ISSUE TITLE
kvmd armbian rk3228a

### ISSUE THREAD

**Issue by aoxo2022** [xe5700/kvmd-armbian#18]
stb android tv box: mxq pro 4k, rk3228a
armbian: armbian 23.05.0-trunk.181.Rk322x-box_bookworm_edge-6.3.1
python: 3.11
dtb: dtb/4.4/rk332x-box.dtb
> overlays=usbhost0 usbhost1 usbhost2 usbhost3
usb male to male adn hdm

if use this method
> apt update
apt install -y git vim make python3-dev gcc
git clone https://github.com/srepac/kvmd-armbian.git
cd kvmd-armbian
./install.sh

then error pyhton 3.9

i try this [http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/Readme.txt](url)
succes install kvmd-armbian

but when kvmd -m

> root@rk322x-box:~/kvmd-armbian# kvmd -m
Traceback (most recent call last):
  File "/usr/local/bin/kvmd", line 6, in <module>
    from kvmd.apps.kvmd import main
  File "/usr/local/lib/python3.11/dist-packages/kvmd/apps/kvmd/__init__.py", line 32, in <module>
    from .info import InfoManager
  File "/usr/local/lib/python3.11/dist-packages/kvmd/apps/kvmd/info/__init__.py", line 29, in <module>
    from .extras import ExtrasInfoSubmanager
  File "/usr/local/lib/python3.11/dist-packages/kvmd/apps/kvmd/info/extras.py", line 35, in <module>
    from .. import sysunit
  File "/usr/local/lib/python3.11/dist-packages/kvmd/apps/kvmd/sysunit.py", line 25, in <module>
    import dbus_next
ModuleNotFoundError: No module named 'dbus_next'

need help!
<img width="938" alt="kvmd" src="https://github.com/xe5700/kvmd-armbian/assets/101029515/cc6fad10-6a2d-43f1-be18-d446844e5b99">

**Comment by crkerx** [comment]
> stb android tv box: mxq pro 4k, rk3228a armbian: armbian 23.05.0-trunk.181.Rk322x-box_bookworm_edge-6.3.1 python: 3.11 dtb: dtb/4.4/rk332x-box.dtb
> 
> > overlays=usbhost0 usbhost1 usbhost2 usbhost3
> > usb male to male adn hdm
> 
> if use this method
> 
> > apt update
> > apt install -y git vim make python3-dev gcc
> > git clone https://github.com/srepac/kvmd-armbian.git
> > cd kvmd-armbian
> > ./install.sh
> 
> then error pyhton 3.9
> 
> i try this [http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/Readme.txt](url) succes install kvmd-armbian
> 
> but when kvmd -m
> 
> > root@rk322x-box:~/kvmd-armbian# kvmd -m
> > Traceback (most recent call last):
> > File "/usr/local/bin/kvmd", line 6, in 
> > from kvmd.apps.kvmd import main
> > File "/usr/local/lib/python3.11/dist-packages/kvmd/apps/kvmd/**init**.py", line 32, in 
> > from .info import InfoManager
> > File "/usr/local/lib/python3.11/dist-packages/kvmd/apps/kvmd/info/**init**.py", line 29, in 
> > from .extras import ExtrasInfoSubmanager
> > File "/usr/local/lib/python3.11/dist-packages/kvmd/apps/kvmd/info/extras.py", line 35, in 
> > from .. import sysunit
> > File "/usr/local/lib/python3.11/dist-packages/kvmd/apps/kvmd/sysunit.py", line 25, in 
> > import dbus_next
> > ModuleNotFoundError: No module named 'dbus_next'
> 
> need help! <img alt="kvmd" width="938" src="https://private-user-images.githubusercontent.com/101029515/238171143-cc6fad10-6a2d-43f1-be18-d446844e5b99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTM4OTMsIm5iZiI6MTcwMTM1MzU5MywicGF0aCI6Ii8xMDEwMjk1MTUvMjM4MTcxMTQzLWNjNmZhZDEwLTZhMmQtNDNmMS1iZTE4LWQ0NDY4NDRlNWI5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQxNDEzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGRjMDRhNzllODQ0MmM3ZjBjMmQyMDdlN2FkNmI4OGY2ODQ2ZWQwYThjMWQyM2E1NzQ5OWNlZGE4NzNlNTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WNnurfjeVi4nZO2P_SGsL1ZT-_mLp8HzFPMz8lqxv0o">
> 
> like this problem [https://forum.armbian.com/topic/26052-mxq-4k-as-pikvm/](url)

Have you solved the above problem yet?

**Comment by remlei** [comment]
the instruction they gave here is very vague and can only be understand by people who know how dtb stuff works specially with armbian, not to mention everything is still based on outdated kernel 4.4 but the logic is still the same.

The specific instruction for rk322x is as follow:

1. Install the latest armbian rk322x minimal release (bookworm as of this post) from the armbian community github, go to rk322x armbian dedicated forum for specific installation based on your storage type (NAND or emmc). 
2. You can ignore the kernel stuff as said on the instruction, since armbian have those OTG kernel features already set but we still need to deal with dtb stuff so instruction depends on:
 
A. For emmc/emcp systems, you just need to enable dtb overlay options so go edit /boot/armbianEnv.txt, Under the "overlay=" line, there should be already some stuff put in there, so all you have to do is add another overlay option there with "usb-otg-peripheral" (without the quotes), make sure every option is separated with (space), after that save the changes and reboot. 

B. For NAND system with jumpstart installed and armbian on SD card, unfortunately the overlay option doesnt work for some odd reason (probably had something to do with the jumpstart), so you need to edit the rk322x-box.dtb file manually. So first we need to decompile the dtb file to dts using the command (you can ignore the warnings):
 
`dtc -I dtb -O dts /boot/dtb/rk322x-box.dtb -o /boot/dtb/rk322x-box.dts`

Edit the rk322x-box.dts file using nano

`nano /boot/dtb/rk322x-box.dts`

Now, press Ctrl + W to look for this line 
`dr_mode = "host";`
replace the host entry to peripheral so it would look like this
`dr_mode = "peripheral";`
Press Ctrl + O and press Enter to save changes and Press Ctrl + X to exit

Now we need to compile the modified dts file back to dtb, to do so use this command, this will overwrite the original rk322x-box.dtb (you can ignore the warnings):

`dtc -I dts -O dtb  /boot/dtb/rk322x-box.dts  -o  /boot/dtb/rk322x-box.dtb`

Reboot after the dtb is compiled.

-=-----

After that you can skip to Step 3 and install kvmd-armbian
