### ISSUE TITLE
Creating `kvmd-webterm` homedir error

### ISSUE THREAD

**Issue by danfmihai** [xe5700/kvmd-armbian#8]
```-> Creating kvmd-webterm homedir
chown: invalid user: ‘kvmd-webterm’
drwxr-xr-x 2 root root 4096 Nov  5 16:40 /home/kvmd-webterm
sed: can't read /lib/systemd/system/kvmd-webterm.service: No such file or directory
chown: invalid user: ‘kvmd-webterm’
Traceback (most recent call last):
  File "/usr/local/bin/kvmd", line 6, in <module>
    from kvmd.apps.kvmd import main
  File "/usr/local/lib/python3.9/dist-packages/kvmd/apps/__init__.py", line 40, in <module>
    from ..plugins.hid import get_hid_class
  File "/usr/local/lib/python3.9/dist-packages/kvmd/plugins/hid/__init__.py", line 31, in <module>
    class BaseHid(BasePlugin):
  File "/usr/local/lib/python3.9/dist-packages/kvmd/plugins/hid/__init__.py", line 67, in BaseHid
    def set_params(self, keyboard_output: (str | None)=None, mouse_output: (str | None)=None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Did kvmd -m run properly?  [y/n] n
Please install missing packages as per the kvmd -m output in another ssh/terminal.
Traceback (most recent call last):
  File "/usr/local/bin/kvmd", line 6, in <module>
    from kvmd.apps.kvmd import main
  File "/usr/local/lib/python3.9/dist-packages/kvmd/apps/__init__.py", line 40, in <module>
    from ..plugins.hid import get_hid_class
  File "/usr/local/lib/python3.9/dist-packages/kvmd/plugins/hid/__init__.py", line 31, in <module>
    class BaseHid(BasePlugin):
  File "/usr/local/lib/python3.9/dist-packages/kvmd/plugins/hid/__init__.py", line 67, in BaseHid
    def set_params(self, keyboard_output: (str | None)=None, mouse_output: (str | None)=None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
Any idea why I get this error? I'm using arambian on a Orangepi PC2. Thanks.

**Comment by xe5700** [comment]
Bug fix by rm /usr/local/lib/python3.9/dist-packages/kvmd, it will auto create account by systemd when you reboot

**Comment by finzzz** [comment]
doesn't work for me
